const BAD_WORDS = [
    "abbo", "alligatorbait", "anal", "analannie", "analsex", "anus", "arse", "arsehole", "assbagger", "assblaster",
    "assclown", "asscowboy", "assfuck", "assfucker", "asshat", "asshole", "assholes", "asshore", "assjockey",
    "asskiss", "asskisser", "assklown", "asslick", "asslicker", "asslover", "assman", "assmonkey", "assmunch",
    "assmuncher", "asspacker", "asspirate", "asspuppies", "assranger", "asswhore", "asswipe", "backdoor",
    "backdoorman", "badfuck", "balllicker", "balls", "ballsack", "banging", "beaner", "beastality", "beastial",
    "beastiality", "beatoff", "beat-off", "beatyourmeat", "beaver", "bestial", "bestiality", "biatch", "bigass",
    "bigbutt", "bitch", "bitcher", "bitches", "bitchez", "bitchin", "bitching", "bitchslap", "bitchy", "blowjob",
    "boang", "bogan", "bohunk", "boner", "boong", "boonga", "boonie", "bootycall", "brothel", "bulldike", "bulldyke",
    "bullshit", "bumblefuck", "bumfuck", "bunga", "bunghole", "butchbabes", "butchdike", "butchdyke", "buttbang",
    "butt-bang", "buttfuck", "butt-fuck", "buttfucker", "butt-fucker", "buttfuckers", "butt-fuckers", "buttpirate",
    "buttplug", "byatch", "cacker", "cameljockey", "cameltoe", "carpetmuncher", "carruth", "cherrypopper",
    "chickslick", "chinaman", "chinamen", "chink", "chinky", "choad", "chode", "clamdigger", "clamdiver", "clit",
    "clitoris", "clogwog", "cock", "cockblock", "cockblocker", "cockcowboy", "cockfight", "cockhead", "cockknob",
    "cocklicker", "cocklover", "cocknob", "cockqueen", "cockrider", "cocksman", "cocksmith", "cocksmoker", "cocksucer",
    "cocksuck", "cocksucked", "cocksucker", "cocksucking", "cocktease", "cohee", "coitus", "coon", "coondog",
    "copulate", "cornhole", "crack", "crackpipe", "crackwhore", "crack-whore", "crotch", "crotchjockey",
    "crotchmonkey", "crotchrot", "cumbubble", "cumfest", "cumjockey", "cumm", "cummer", "cumming", "cumqueen",
    "cumshot", "cunilingus", "cunillingus", "cunn", "cunnilingus", "cunntt", "cunt", "cunteyed", "cuntfuck",
    "cuntfucker", "cuntlick", "cuntlicker", "cuntlicking", "cuntsucker", "cybersex", "cyberslimer", "dago", "darkie",
    "darky", "datnigga", "deapthroat", "deepthroat", "dego", "devilworshipper", "dick", "dickbrain", "dickforbrains",
    "dickhead", "dickless", "dicklick", "dicklicker", "dickman", "dickwad", "dickweed", "dike", "dildo", "dingleberry",
    "dixiedike", "dixiedyke", "doggiestyle", "doggystyle", "dragqueen", "dragqween", "dripdick", "dumbfuck", "dyefly",
    "dyke", "easyslut", "eatballs", "eatme", "eatpussy", "ecstacy", "ejaculate", "ejaculated", "ejaculating",
    "ejaculation", "enema", "erect", "erection", "facefucker", "fagging", "faggot", "fagot", "fannyfucker", "fastfuck",
    "fatfuck", "fatfucker", "fatso", "fckcum", "felatio", "felch", "felcher", "felching", "fellatio", "feltch",
    "feltcher", "feltching", "fetish", "fingerfuck", "fingerfucked", "fingerfucker", "fingerfuckers", "fingerfucking",
    "fister", "fistfuck", "fistfucked", "fistfucker", "fistfucking", "fisting", "flange", "flasher", "flydie",
    "flydye", "footfuck", "footfucker", "footlicker", "footstar", "forni", "fornicate", "foursome", "freakfuck",
    "freakyfucker", "freefuck", "fubar", "fucck", "fuck", "fucka", "fuckable", "fuckbag", "fuckbuddy", "fucked",
    "fuckedup", "fucker", "fuckers", "fuckface", "fuckfest", "fuckfreak", "fuckfriend", "fuckhead", "fuckher",
    "fuckin", "fuckina", "fucking", "fuckingbitch", "fuckinnuts", "fuckinright", "fuckit", "fuckknob", "fuckme",
    "fuckmehard", "fuckmonkey", "fuckoff", "fuckpig", "fucks", "fucktard", "fuckwhore", "fuckyou", "fudgepacker",
    "fuks", "funfuck", "fuuck", "gangbang", "gangbanged", "gangbanger", "gatorbait", "gaymuthafuckinwhore", "gaysex",
    "ginzo", "gipp", "givehead", "goddamnmuthafucker", "goldenshower", "gonorrehea", "gook", "goyim", "greaseball",
    "gringo", "grostulation", "gubba", "gummer", "gypo", "gypp", "gyppie", "gyppo", "gyppy", "handjob", "hapa",
    "hardon", "headfuck", "hebe", "heeb", "herpes", "hillbillies", "hindoo", "hiscock", "hitler", "hitlerism",
    "hitlerist", "hodgie", "hoes", "holestuffer", "homo", "homobangers", "homosexual", "honger", "honkers", "honkey",
    "honky", "hooker", "hookers", "hore", "horney", "horniest", "horny", "horseshit", "hosejob", "hoser", "hotpussy",
    "hottotrot", "hummer", "hussy", "hustler", "hymen", "hymie", "iblowu", "ikey", "incest", "insest", "intercourse",
    "interracial", "intheass", "inthebuff", "jackoff", "jackshit", "jerkoff", "jiga", "jigaboo", "jigg", "jigga",
    "jiggabo", "jigger", "jihad", "jijjiboo", "jimfish", "jism", "jizim", "jizjuice", "jizm", "jizz", "jizzim",
    "jizzum", "juggalo", "junglebunny", "kaffer", "kaffir", "kaffre", "kafir", "kanake", "kigger", "kike", "kock",
    "kondum", "koon", "kraut", "kumbubble", "kumbullbe", "kummer", "kumming", "kums", "kunilingus", "kunnilingus",
    "kunt", "kyke", "lapdance", "lesbain", "lesbayn", "lesbian", "lesbin", "lesbo", "lezbe", "lezbefriends", "lezbo",
    "lezz", "lezzo", "licker", "lickme", "limey", "limpdick", "limy", "livesex", "lolita", "lovebone", "lovegoo",
    "lovegun", "lovejuice", "lovemuscle", "lovepistol", "loverocket", "lubejob", "luckycammeltoe", "lugan", "lynch",
    "macaca", "magicwand", "manhater", "manpaste", "mastabate", "mastabater", "masterbate", "mastrabator",
    "masturbate", "masturbating", "mattressprincess", "meatbeatter", "meatrack", "mgger", "mggor", "mickeyfinn",
    "milf", "mockey", "mockie", "mocky", "mofo", "moky", "molest", "molestation", "molester", "molestor", "moneyshot",
    "mooncricket", "mosshead", "mothafuck", "mothafucka", "mothafuckaz", "mothafucked", "mothafucker", "mothafuckin",
    "mothafucking", "mothafuckings", "motherfuck", "motherfucked", "motherfucker", "motherfuckin", "motherfucking",
    "motherfuckings", "motherlovebone", "muff", "muffdive", "muffdiver", "muffindiver", "mufflikcer", "mulatto",
    "muncher", "munt", "nastybitch", "nastyho", "nastyslut", "nastywhore", "nazi", "necro", "negro", "negroes",
    "negroid", "negro's", "nigg", "nigga", "niggah", "niggaracci", "niggaz", "nigger", "niggerhead", "niggerhole",
    "niggers", "nigger's", "niggor", "niggur", "niglet", "nignog", "nigr", "nigra", "nigre", "nipplering", "nlgger",
    "nlggor", "nofuckingway", "nook", "nookey", "nookie", "noonan", "nooner", "nudger", "nutfucker", "orgasim",
    "orgasm", "orgies", "orgy", "paki", "palesimian", "payo", "pearlnecklace", "pecker", "peckerwood", "peehole",
    "pee-pee", "peepshow", "peepshpw", "pendy", "peni5", "penile", "penis", "penises", "penthouse", "perv", "phonesex",
    "phuk", "phuked", "phuking", "phukked", "phukking", "phungky", "phuq", "picaninny", "piccaninny", "pickaninny",
    "piker", "pikey", "piky", "pimp", "pimped", "pimper", "pimpjuic", "pimpjuice", "pimpsimp", "pindick", "pocha",
    "pocho", "pocketpool", "polack", "poon", "poontang", "poorwhitetrash", "popimp", "porchmonkey", "porn",
    "pornflick", "pornking", "porno", "pornography", "pornprincess", "pric", "prick", "prickhead", "prostitute",
    "pu55i", "pu55y", "pube", "pubic", "pubiclice", "pudboy", "pudd", "puddboy", "puntang", "purinapricness", "puss",
    "pussie", "pussies", "pussy", "pussycat", "pussyeater", "pussyfucker", "pussylicker", "pussylips", "pussylover",
    "pussypounder", "pusy", "quashie", "queef", "queer", "quim", "ra8s", "raghead", "rape", "raped", "raper", "rapist",
    "rearend", "rearentry", "rectum", "redlight", "redneck", "reestie", "rentafuck", "rere", "retard", "retarded",
    "rimjob", "rimming", "roundeye", "rump", "russki", "russkie", "sadis", "sadom", "samckdaddy", "sandm",
    "sandnigger", "satan", "scag", "scallywag", "schlong", "scrotum", "scum", "semen", "seppo", "sexed", "sexfarm",
    "sexhound", "sexhouse", "sexing", "sexkitten", "sexpot", "sexslave", "sextogo", "sextoy", "sextoys", "sexwhore",
    "sexy", "sexymoma", "sexy-slim", "shag", "shaggin", "shagging", "shat", "shav", "shawtypimp", "sheeney", "shhit",
    "shinola", "shit", "shitcan", "shitdick", "shite", "shiteater", "shited", "shitface", "shitfaced", "shitfit",
    "shitforbrains", "shitfuck", "shitfucker", "shitfull", "shithapens", "shithappens", "shithead", "shithouse",
    "shiting", "shitlist", "shitola", "shitoutofluck", "shits", "shitstain", "shitted", "shitter", "shitting",
    "shitty", "shortfuck", "sixsixsix", "sixtynine", "sixtyniner", "skank", "skankbitch", "skankfuck", "skankwhore",
    "skanky", "skankybitch", "skankywhore", "skinflute", "skum", "skumbag", "slant", "slanteye", "slapper",
    "sleezebag", "sleezeball", "slideitin", "slimeball", "slimebucket", "slopehead", "slopey", "slopy", "slut",
    "sluts", "slutt", "slutting", "slutty", "slutwear", "slutwhore", "smackthemonkey", "smut", "snatch", "snatchpatch",
    "snownigger", "sodom", "sodomise", "sodomite", "sodomize", "sodomy", "sonofabitch", "sonofbitch", "sooty",
    "spaghettibender", "spaghettinigger", "spank", "spankthemonkey", "sperm", "spermacide", "spermbag", "spermhearder",
    "spermherder", "spic", "spick", "spig", "spigotty", "spik", "splittail", "spooge", "spreadeagle", "spunk",
    "spunky", "squaw", "strapon", "stripclub", "stupidfuck", "stupidfucker", "suckdick", "suckme", "suckmyass",
    "suckmydick", "suckmytit", "suckoff", "swallower", "swalow", "swastika", "taff", "tarbaby", "tard", "teste",
    "testicle", "testicles", "thicklips", "thirdleg", "threesome", "threeway", "timbernigger", "titbitnipply",
    "titfuck", "titfucker", "titfuckin", "titjob", "titlicker", "titlover", "tits", "tittie", "titties", "titty",
    "tongethruster", "tonguethrust", "tonguetramp", "tosser", "towelhead", "trailertrash", "trannie", "tranny",
    "transexual", "transsexual", "transvestite", "trisexual", "tuckahoe", "tunneloflove", "twat", "twink", "twinkie",
    "twobitwhore", "unfuckable", "upskirt", "uptheass", "upthebutt", "vagina", "vaginal", "vibrater", "vibrator",
    "virginbreaker", "vulva", "wank", "wanker", "wanking", "wetb", "wetback", "wetspot", "whigger", "whiskeydick",
    "whiskydick", "whitenigger", "whitetrash", "whitey", "whop", "whore", "whorefucker", "whorehouse", "wigger",
    "williewanker", "zigabo", "zipperhead"
];

window.filterBadWords = function(text) {
    if (!text || typeof BAD_WORDS === 'undefined') return text;
    // Create regex once if not already created
    if (!window._profanityRegex) {
        var escaped = BAD_WORDS.filter(w => w).map(w => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
        window._profanityRegex = new RegExp('\\b(' + escaped.join('|') + ')\\b', 'gi');
    }
    return text.replace(window._profanityRegex, function(match) {
        var blocks = '';
        var len = Math.min(match.length, 5);
        for (var i = 0; i < len; i++) blocks += '█';
        return blocks;
    });
};
